### ISSUE TITLE
test usb-stick scripts

### ISSUE THREAD

**Issue by koppi** [koppi/mk#5]
Hi @zultron, today I created some simple scripts to build a 4GB Machinekit live usb stick for testing, see:

https://github.com/koppi/mk/tree/master/usb-stick

What do you think about this?

**Comment by zultron** [comment]
Seems interesting.  I'm unable to read the `x` script, though.  Can you put some line breaks in there?

```
foo \
    arg1 arg2 \
    arg3 arg4
```

**Comment by zultron** [comment]
Ok, my eyeballs are still shaking, but got through it.

I'm not familiar with [`grml-debootstrap`](https://grml.org/grml-debootstrap/).  So once `x` is done, you can run `dd if=machinekit-$RELEASE.img of=/dev/[flashdrivepartition]`, stick the flash drive in a computer and it will boot?  That's a nice touch, running it in `qemu`.

Keyboard layout should be `dvorak`, not `de`.  ;)

What do you want to do with this?

**Comment by koppi** [comment]
@zultron not sure, what to do with this. Perhaps we could add a download area for x86 and x86_64 usb stick images somewhere on machinekit.io and let them be built by some buildbot infrastructure?!

**Comment by zultron** [comment]
I've heard a few folks asking for Machinekit live images.

The machinekit.io site and the project in general don't ship binaries.  That's why package repos are hosted by 3rd parties at http://deb.dovetail-automata.com/ and http://0ptr.link/raspbian.  As for me, I'm a little overwhelmed with package maintenance already.

Here are a couple of possibilities:
- Low maintenance:  Let users build their own USB stick images.  Fix up this code (e.g. give scripts meaningful names, add line breaks, move to `/debian` subdirectory, add documentation), and submit as a PR.
- High maintenance:  Become a Machinekit live USB image vendor!  Build them manually or automatically (I'll be happy to advise), and then you can make them available on your own site.  We could add pointers and documentation to your contribution on the [Debian packages page](http://www.machinekit.io/docs/packages-debian/).
